package com.pianopath.app;

import android.app.*;import android.os.*;import android.graphics.Color;import android.graphics.Typeface;import android.media.midi.*;import android.view.*;import android.widget.*;import java.io.IOException;import java.util.*;

public class MainActivity extends Activity {
  final int NAVY=Color.rgb(23,33,58), BLUE=Color.rgb(102,120,255), BG=Color.rgb(246,247,251), GREEN=Color.rgb(43,191,156), MUTED=Color.rgb(105,115,137);
  LinearLayout root,content; TextView xpText,midiText; int xp=0,currentLesson=0; Set<Integer> done=new HashSet<>();
  MidiManager midi; final List<MidiDevice> devices=new ArrayList<>(); final List<MidiOutputPort> ports=new ArrayList<>(); int expected=-1;
  final String[] lessons={"Welcome to PianoPath","Find the two black keys","Find middle C","Play C three times","Play C–D–E","Keep four steady beats","Mini piece: C–D–E–D–C","Unit checkpoint"};
  final int[][] targets={{},{},{60},{60,60,60},{60,62,64},{},{60,62,64,62,60},{60,62,64,65,67,65,64,62,60}};
  final String[] sections={"Meet the Piano","First Right-Hand Notes","Expanding the Right Hand","First Left-Hand Notes","Playing With Both Hands","Rhythm Foundations","Intervals and Reading","First Chords","Sharps, Flats and New Keys","Pedal and Expression","Beginner Classical Repertoire","Beginner Graduation","Scales and Thumb Crossing","Chord Inversions","Broken Chords and Arpeggios","Hand Independence","Minor Keys","Faster Rhythm","Ornamentation","Early Intermediate Repertoire","Two-Octave Technique","Polyphonic Playing","Voicing and Tone","Leaps and Keyboard Geography","Advanced Pedalling","Classical Forms","Intermediate Repertoire","Intermediate Graduation","Advanced Scales and Arpeggios","Octaves and Repeated Notes","Complex Rhythm","Romantic Expression","Impressionist Technique","Classical and Baroque Style","Upper-Intermediate Repertoire","Advanced Chord Technique","Double Notes","Advanced Polyphony","Virtuoso Movement","Advanced Interpretation","Memorisation and Performance","Advanced Repertoire","Final Piano Mastery"};

  public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(NAVY);getWindow().setNavigationBarColor(Color.WHITE);load();midi=(MidiManager)getSystemService(MIDI_SERVICE);showLearn();refreshMidi();}
  TextView text(String s,int size,int color,boolean bold){TextView v=new TextView(this);v.setText(s);v.setTextSize(size);v.setTextColor(color);v.setPadding(dp(16),dp(10),dp(16),dp(10));if(bold)v.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return v;}
  Button button(String s){Button b=new Button(this);b.setText(s);b.setTextSize(16);b.setAllCaps(false);b.setTextColor(Color.WHITE);b.setBackgroundColor(BLUE);b.setPadding(dp(14),dp(12),dp(14),dp(12));return b;}
  int dp(int v){return (int)(v*getResources().getDisplayMetrics().density+.5f);} void addSpace(int h){Space s=new Space(this);content.addView(s,new LinearLayout.LayoutParams(1,dp(h)));}
  void shell(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);setContentView(root);LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);top.setPadding(dp(14),dp(10),dp(14),dp(10));top.setBackgroundColor(Color.WHITE);TextView brand=text("♪  PianoPath",21,NAVY,true);top.addView(brand,new LinearLayout.LayoutParams(0,dp(54),1));xpText=text("✦ "+xp,15,NAVY,true);top.addView(xpText);root.addView(top);ScrollView sv=new ScrollView(this);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(dp(14),dp(14),dp(14),dp(100));sv.addView(content);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));LinearLayout nav=new LinearLayout(this);nav.setGravity(Gravity.CENTER);String[] ns={"Learn","Course","Piano"};for(String n:ns){Button x=new Button(this);x.setText(n);x.setAllCaps(false);x.setOnClickListener(v->{if(n.equals("Learn"))showLearn();else if(n.equals("Course"))showCourse();else showMidi();});nav.addView(x,new LinearLayout.LayoutParams(0,dp(58),1));}root.addView(nav);}
  void hero(String title,String sub){LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(dp(18),dp(18),dp(18),dp(18));card.setBackgroundColor(NAVY);TextView t=text(title,28,Color.WHITE,true);TextView s=text(sub,15,Color.rgb(220,226,241),false);card.addView(t);card.addView(s);content.addView(card,new LinearLayout.LayoutParams(-1,-2));}
  void showLearn(){shell();hero("Meet the Keyboard","Section 1 · Unit 1 — your first eight ordered lessons.");addSpace(16);content.addView(text(done.size()+" of 8 lessons complete",17,NAVY,true));for(int i=0;i<lessons.length;i++){Button b=button((done.contains(i)?"✓ ":i>currentLesson?"🔒 ":"♪ ")+(i+1)+". "+lessons[i]);boolean open=i<=currentLesson||done.contains(i);b.setEnabled(open);if(done.contains(i))b.setBackgroundColor(GREEN);int k=i;b.setOnClickListener(v->openLesson(k));content.addView(b,new LinearLayout.LayoutParams(-1,dp(62)));addSpace(10);}}
  void showCourse(){shell();hero("The complete journey","43 ordered sections from first note to advanced performance.");for(int i=0;i<sections.length;i++){TextView v=text((i==0?"▶ ":"🔒 ")+(i+1)+". "+sections[i],17,i==0?NAVY:MUTED,true);v.setBackgroundColor(Color.WHITE);content.addView(v,new LinearLayout.LayoutParams(-1,dp(60)));addSpace(8);}}
  void showMidi(){shell();hero("Connect your electric piano","Use USB MIDI for exact note detection and low latency.");midiText=text(ports.isEmpty()?"No MIDI piano connected":"Connected: "+ports.size()+" MIDI input(s)",18,ports.isEmpty()?MUTED:GREEN,true);content.addView(midiText);Button r=button("Refresh MIDI devices");r.setOnClickListener(v->refreshMidi());content.addView(r,new LinearLayout.LayoutParams(-1,dp(60)));addSpace(12);content.addView(text("Your piano should have USB TO HOST, USB MIDI, or MIDI OUT. Use a USB-C data cable or OTG adapter with the phone.",15,MUTED,false));}
  void openLesson(int i){currentLesson=i;expected=0;root.removeAllViews();root.setBackgroundColor(Color.WHITE);LinearLayout page=new LinearLayout(this);page.setOrientation(LinearLayout.VERTICAL);page.setPadding(dp(18),dp(18),dp(18),dp(18));root.addView(page,new LinearLayout.LayoutParams(-1,-1));TextView title=text(lessons[i],28,NAVY,true);page.addView(title);TextView info=text(instruction(i),16,MUTED,false);page.addView(info);Space sp=new Space(this);page.addView(sp,new LinearLayout.LayoutParams(1,dp(20)));TextView status=text(statusText(i),22,NAVY,true);status.setGravity(Gravity.CENTER);status.setTag("status");page.addView(status,new LinearLayout.LayoutParams(-1,0,1));if(i==1){Button answer=button("I found the group of 2 black keys");answer.setOnClickListener(v->finish(i));page.addView(answer,new LinearLayout.LayoutParams(-1,dp(62)));}else if(i==5){Button tap=button("TAP");final long[] times=new long[4];final int[] count={0};tap.setOnClickListener(v->{if(count[0]<4)times[count[0]++]=System.currentTimeMillis();status.setText(count[0]+" / 4 beats");if(count[0]==4){long a=times[1]-times[0],b=times[2]-times[1],c=times[3]-times[2],avg=(a+b+c)/3;if(avg>250&&avg<1500&&Math.max(Math.abs(a-avg),Math.max(Math.abs(b-avg),Math.abs(c-avg)))<avg*.35)finish(i);else{count[0]=0;status.setText("Try again — keep the spacing even");}}});page.addView(tap,new LinearLayout.LayoutParams(-1,dp(100)));}else if(targets[i].length==0){Button go=button("Continue");go.setOnClickListener(v->finish(i));page.addView(go,new LinearLayout.LayoutParams(-1,dp(62)));}else{LinearLayout keys=new LinearLayout(this);int[] notes={60,62,64,65,67};String[] names={"C","D","E","F","G"};for(int k=0;k<notes.length;k++){Button key=button(names[k]);key.setBackgroundColor(Color.WHITE);key.setTextColor(NAVY);int n=notes[k];key.setOnClickListener(v->note(n));keys.addView(key,new LinearLayout.LayoutParams(0,dp(150),1));}page.addView(keys);TextView hint=text("Play on the on-screen keys or your connected piano.",14,MUTED,false);page.addView(hint);}}
  String instruction(int i){switch(i){case 0:return "Learn the keyboard pattern, posture, and finger numbers.";case 1:return "Black keys repeat in groups of two and three. Find a group of two.";case 2:return "Middle C is the C nearest the centre of the keyboard.";case 5:return "Tap four evenly spaced beats without rushing.";default:return "Play the notes in order. The app checks every note.";}}
  String statusText(int i){if(targets[i].length==0)return i==1?"Look across your keyboard":"Ready when you are";return "Next: "+name(targets[i][0])+"   0 / "+targets[i].length;}
  void note(int n){if(currentLesson<0||targets[currentLesson].length==0)return;int[] seq=targets[currentLesson];if(n==seq[expected]){expected++;TextView s=(TextView)root.findViewWithTag("status");if(expected>=seq.length){s.setText("✓ Lesson complete");new Handler().postDelayed(()->finish(currentLesson),500);}else s.setText("Next: "+name(seq[expected])+"   "+expected+" / "+seq.length);}else Toast.makeText(this,"That was "+name(n)+" — try "+name(seq[expected]),Toast.LENGTH_SHORT).show();}
  String name(int n){String[] x={"C","C♯","D","D♯","E","F","F♯","G","G♯","A","A♯","B"};return x[n%12]+(n/12-1);}
  void finish(int i){if(!done.contains(i)){done.add(i);xp+=10;if(i==currentLesson&&currentLesson<7)currentLesson++;save();}Toast.makeText(this,"Lesson complete · +10 XP",Toast.LENGTH_SHORT).show();showLearn();}
  void load(){android.content.SharedPreferences p=getSharedPreferences("progress",0);xp=p.getInt("xp",0);currentLesson=p.getInt("current",0);String raw=p.getString("done","");if(!raw.isEmpty())for(String s:raw.split(","))try{done.add(Integer.parseInt(s));}catch(Exception ignored){}}
  void save(){StringBuilder s=new StringBuilder();for(int i:done){if(s.length()>0)s.append(',');s.append(i);}getSharedPreferences("progress",0).edit().putInt("xp",xp).putInt("current",currentLesson).putString("done",s.toString()).apply();}
  void refreshMidi(){if(midi==null)return;closeMidi();for(MidiDeviceInfo info:midi.getDevices()){if(info.getOutputPortCount()<1)continue;midi.openDevice(info,d->{if(d==null)return;devices.add(d);for(int p=0;p<info.getOutputPortCount();p++){MidiOutputPort port=d.openOutputPort(p);if(port!=null){port.connect(new MidiReceiver(){public void onSend(byte[] data,int off,int count,long t){for(int i=off;i+2<off+count;i++){int st=data[i]&255;if((st&240)==144&&(data[i+2]&255)>0){int n=data[i+1]&255;runOnUiThread(()->note(n));i+=2;}}}});ports.add(port);}}runOnUiThread(()->{if(midiText!=null)midiText.setText("Connected: "+ports.size()+" MIDI input(s)");});},new Handler(Looper.getMainLooper()));}}
  void closeMidi(){for(MidiOutputPort p:ports)try{p.close();}catch(IOException ignored){}ports.clear();for(MidiDevice d:devices)try{d.close();}catch(IOException ignored){}devices.clear();}
  protected void onDestroy(){closeMidi();super.onDestroy();}
}
